### PR TITLE
include id in qg output

### PR DESCRIPTION
**Pull request by jdpsen**
This closes the issue https://github.com/primeqa/primeqa/issues/280 .

It makes changes to the passageqg generation pipeline where it shows the context passage and id of the passage for each QA pair generated.
TableQG generation pipeline is modified to keep the generation API structure uniform .

question generation API now accepts an optional list of IDs aligned with the set of tables or passages given as input.
Note:  this is a modified PR which builds over existing main without the changes about reorganizing run_* scripts

### CODE REVIEW

**Comment by ma-sultan** [comment]
@jdpsen In the following output structure, I wonder if `context_id` or something similar should replace the key `id` because it is a bit unclear currently what the id applies to: 


```
[{'id': 'abcID123',
  'context': 'Sachin tendulkar was an Indian cricketer born in Mumbai. He had a record of 100 centuries in his international carrier. He scored nearly 350000 international runs',
  'question': 'What country did Sachin tendulkar play?',
  'answer': 'Indian'},
 {'id': 'abcID123',
  'context': 'Sachin tendulkar was an Indian cricketer born in Mumbai. He had a record of 100 centuries in his international carrier. He scored nearly 350000 international runs',
  'question': 'How many runs did Sachin tendulkar have?',
  'answer': '100 centuries'},
 {'id': 'xyzID456',
  'context': 'Симби́рская губе́рния (с 1924 года Ульяновская губерния)\xa0— административно-территориальнаяединица Российской империи, Российской республики и РСФСР, существовавшая в 1796—1928 годах.Губернский город\xa0— Симбирск (с 1924 года Ульяновск)',
  'question': 'Как называется Губернский город?',
  'answer': 'Симбирск'},
 {'id': 'xyzID456',
  'context': 'Симби́рская губе́рния (с 1924 года Ульяновская губерния)\xa0— административно-территориальнаяединица Российской империи, Российской республики и РСФСР, существовавшая в 1796—1928 годах.Губернский город\xa0— Симбирск (с 1924 года Ульяновск)',
  'question': 'Как называется Симбирская губерния?',
  'answer': 'Ульяновская губерния'}]
```

**Review by bhavani105 — APPROVED** [review]
LGTM

**Comment by jdpsen** [comment]
> @jdpsen In the following output structure, I wonder if `context_id` or something similar should replace the key `id` because it is a bit unclear currently what the id applies to:
> 
> ```
> [{'id': 'abcID123',
>   'context': 'Sachin tendulkar was an Indian cricketer born in Mumbai. He had a record of 100 centuries in his international carrier. He scored nearly 350000 international runs',
>   'question': 'What country did Sachin tendulkar play?',
>   'answer': 'Indian'},
>  {'id': 'abcID123',
>   'context': 'Sachin tendulkar was an Indian cricketer born in Mumbai. He had a record of 100 centuries in his international carrier. He scored nearly 350000 international runs',
>   'question': 'How many runs did Sachin tendulkar have?',
>   'answer': '100 centuries'},
>  {'id': 'xyzID456',
>   'context': 'Симби́рская губе́рния (с 1924 года Ульяновская губерния)\xa0— административно-территориальнаяединица Российской империи, Российской республики и РСФСР, существовавшая в 1796—1928 годах.Губернский город\xa0— Симбирск (с 1924 года Ульяновск)',
>   'question': 'Как называется Губернский город?',
>   'answer': 'Симбирск'},
>  {'id': 'xyzID456',
>   'context': 'Симби́рская губе́рния (с 1924 года Ульяновская губерния)\xa0— административно-территориальнаяединица Российской империи, Российской республики и РСФСР, существовавшая в 1796—1928 годах.Губернский город\xa0— Симбирск (с 1924 года Ульяновск)',
>   'question': 'Как называется Симбирская губерния?',
>   'answer': 'Ульяновская губерния'}]
> ```

Corrected it to context_id.

**Review by ma-sultan — APPROVED** [review]
Looks good.

**Pull request merged**
