### PR TITLE
Two ColBERT engine bug fixes

### LINKED ISSUE #170: Calculated maxsteps not used in training loop
_jbross created the following on Jun 09:_  

 Initially the maxsteps is calculated as minimum between user provided `config.maxsteps` and maxsteps derived from user provided `config.epochs` in [line 260](https://github.ibm.com/ai-foundation/OneQA/blob/master/oneqa/ir/dense/colbert_top/colbert/training/training.py#L260):
```
maxsteps = min(config.maxsteps, math.ceil((config.epochs * len(reader)) / (config.bsize * config.nranks)))
```

However, in the actual loop over the training batches in [line 383](https://github.ibm.com/ai-foundation/OneQA/blob/master/oneqa/ir/dense/colbert_top/colbert/training/training.py#L383) it uses the `config.maxsteps` instead of the calculated `maxsteps` value:

```
for batch_idx, BatchSteps in zip(range(start_batch_idx, config.maxsteps), reader):
```

This does not seem to be intended, as the `config.epochs` has no effect at all. 

_Original issue: https://github.ibm.com/ai-foundation/PrimeQA/issues/228_

### PR DESCRIPTION
**Pull request by franzmpub**
# Pull Request      

## What does this PR do?

Two ColBERT engine bug fixes:
1. `maxsteps` handling in training.py (Issue 170), 
2. `unqiue` typo in create_triples.py (PR 431)"

```Closes #170, #431 ```       
 
## Versioning

When opening a PR to make changes to PrimeQA (i.e. `primeqa/`) master, be sure to increment the version following
[semantic versioning](https://semver.org/).  The VERSION is stored [here](https://github.com/primeqa/primeqa/blob/main/VERSION) 
and is incremented using `bump2version {patch,minor,major}` as described in the (development guide documentation)[development.html].

 - [ ] Have you updated the VERSION?
 - [ ] Or does this PR not change the `primeqa` package or was not into master?

After pulling in changes from master to an existing PR, ensure the VERSION is updated appropriately.
This may require bumping the version again if it has been previously bumped.

If you're not quite ready yet to post a PR for review, feel free to open a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

### After Merging
If merging into master and VERSION was updated, after this PR is merged:
- [ ] [Create a release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) from the master with version equal to [VERSION](https://github.com/primeqa/primeqa/blob/main/VERSION)
- [ ] Not merging to master or VERSION not updated

### Checklist

Review the following and mark as completed:
- [x] [Tag an issue or issues](#what-does-this-pr-do) this PR addresses.
- [x] Added [description](#description) of changes proposed.
- [x] Review requested as [appropriate](#request-review).
- [x] Version bumped as [appropriate](#Versioning).
- [ ] New classes, methods, and functions documented.
- [ ] Documentation for modified code is updated.
- [ ] Built documentation to confirm it renders as expected (see [here](development.md)).
- [ ] Code cleaned up and commented out code removed.
- [ ] Tests added to ensure all functionalities tested at >= 60% unit test coverage (see [here](development.md)).
- [ ] Code cleaned up and commented out code removed.
- [ ] Release created [as needed](#after-merging) after merging.

### CODE REVIEW

**Review by kpfadnis — APPROVED** [review]
LGTM. 

@franzmpub Please verify  via RPC call that ColBERTRetriever doesn't suffer regression due to this change.

**Review by hrojek — APPROVED** [review]
LGTM

**Comment by franzmpub** [comment]
> LGTM.
> 
> @franzmpub Please verify via RPC call that ColBERTRetriever doesn't suffer regression due to this change.

@kpfadnis The changes influence training only (which I've verified), as opposed to retrieval as exposed through Services.

**Review by bhavani105 — APPROVED** [review]
LGTM

**Pull request merged**
