### PR TITLE
Allow to select the seed of the random number generators  

### LINKED ISSUE #301: Allow to select the seed of the random number generators
allow to select the seed of the random number generators using --rng_seed argument

### PR DESCRIPTION
**Pull request by franzmpub**
# PrimeQA Pull Request

## What does this PR do?
Allow to select the seed of the random number generators using --rng_seed argument"
Closes #301 

## Description

Two points:

1. For training, the RNG seeds are set both in `launcher.py` and `training.py` as before, to allow to reproduce older results.

2. The default values are set both in  
`infra/config/settings.py:173:    rng_seed: int = DefaultVal(12345)`
and
`utils/parser.py:22:        self.add_argument('--rng_seed', dest='rng_seed', default=12345, type=int)`
which takes precedence.
This could be eventually resolved for all the arguments.  

### Request Review

Be sure to **request a review** from one or more reviewers (unless the PR is to an unprotected branch).

## Versioning

When opening a PR to make changes to PrimeQA (i.e. `primeqa/`) master, be sure to increment the version following
[semantic versioning](https://semver.org/).  The VERSION is stored [here](https://github.com/primeqa/primeqa/blob/main/VERSION) 
and is incremented using `bump2version {patch,minor,major}` as described in the development guide documentation (https://github.com/primeqa/primeqa/blob/main/docs/development.md).

 - [x] Have you updated the VERSION?
 - [ ] Or does this PR not change the `primeqa` package or was not into master?

After pulling in changes from master to an existing PR, ensure the VERSION is updated appropriately.
This may require bumping the version again if it has been previously bumped.

If you're not quite ready yet to post a PR for review, feel free to open a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

### After Merging
If merging into master and VERSION was updated, after this PR is merged:
- [ ] [Create a release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) from the master with version equal to [VERSION](https://github.com/primeqa/primeqa/blob/main/VERSION)
- [ ] Not merging to master or VERSION not updated

## Checklist

Review the following and mark as completed:
- [x] [Tag an issue or issues](#what-does-this-pr-do) this PR addresses.
- [x] Added [description](#description) of changes proposed.
- [x] Review requested as [appropriate](#request-review).
- [x] Version bumped as [appropriate](#Versioning).
- [x] New classes, methods, and functions documented.
- [x] Documentation for modified code is updated.
- [x] Built documentation to confirm it renders as expected (see https://github.com/primeqa/primeqa/blob/main/docs/development.md).
- [x] Code cleaned up and commented out code removed.
- [x] Tests added to ensure all functionalities tested at >= 60% unit test coverage (see https://github.com/primeqa/primeqa/blob/main/docs/development.md).
- [x] Code cleaned up and commented out code removed.
- [x] Release created [as needed](#after-merging) after merging.

### CODE REVIEW

**Review by bhavani105 — APPROVED** [review]
LGTM

**Comment by yulongl-ibm** [comment]
@franzmpub Just to make sure, you have tested providing seed from the argument and the result was reproducible in different runs, is that correct?

**Review by jsmcibm — APPROVED** [review]
LGTM

**Comment by franzmpub** [comment]
> @franzmpub Just to make sure, you have tested providing seed from the argument and the result was reproducible in different runs, is that correct?

@yulongl-ibm Yes, I've verified that the sequences of model representation are identical for runs for a given seed (and different for different seeds too :-) )

**Review by yulongl-ibm — APPROVED** [review]

**Pull request merged**
