### PR TITLE
Google rouge

### PR DESCRIPTION
**Pull request by seirasto**
# Pull Request      

Add Google HF rouge as a metric in addition to Kilt Rouge. I recommend we prefer the Google HF version

### CODE REVIEW

**Review by mihaela-bornea — APPROVED** [review]
LGTM

**Review by rongzhangibm — APPROVED** [review]
LGTM

**Review by bhavani105 — APPROVED** [review]
LGTM

**Comment by rongzhangibm** [comment]
Flan T5-XXL results: (using trainer.eval

|           |                 main-branch-rougeL  |  kilt-rougeL |   google-rougeL
|-|-|-|-|
|zeroshot (closed-book)     |       6.30          |     6.30      |       7.31 |
|zeroshot (with passage)     |     27.08         |     27.08      |      26.88 |
|fine-tuning            |          47.61      |        47.61      |      49.02 |

**Pull request merged**
